### ISSUE TITLE
Запись на тестирование

### ISSUE THREAD

**Issue by Mazian** [FantLab/FantLab-iOS#2]
Прочитал про разработку этого и первые экраны
https://github.com/FantLab/FantLab-API/issues/42

А как можно получить приложение на тестирование на свой iphone se?

Интересно посмотреть UX. Уж больно видео понравилось
(в идеале потом может и поковыряться, хотя у меня вообще ноль опыта в xcode).

**Comment by geor-kasapidi** [comment]
@Mazian мне нужен будет твой UDID для начала. Я на днях настрою сборки проекта, чтобы можно было их скачивать на девайсы. И после этого нужно будет зарегаться как тестер в фабрике (скорее всего). Чтобы быстрее решать такие вопросы - можешь смело писать мне в телегу - nseven :)

**Comment by geor-kasapidi** [comment]
а по поводу что-то поконтрибьютить, то предлагаю подождать немного - я по ходу дела стандартизирую правила разработки модулей и можно будет взять на разработку какой-нить простенький экран (например профиль пользователя с основной инфой). Сложного кода в самих модулях не должно быть, так что проблем не должно возникнуть :)

**Comment by Mazian** [comment]
Отлично, спасибо!
Иду записываться в тестеры, а дальше - посмотрим, ага! =)
